# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-16 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labApp', '0005_auto_20171216_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='images',
            field=models.ImageField(blank=True, default='user_icon.png', upload_to='user/', verbose_name='Фотография'),
        ),
    ]
