# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-17 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labApp', '0009_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='images',
            field=models.ImageField(blank=True, default='user/user_icon.png', upload_to='user/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='prodact',
            name='images',
            field=models.ImageField(blank=True, default='prodact/prodact_icon.png', upload_to='prodact/', verbose_name='Фотография'),
        ),
    ]
