# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-17 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labApp', '0012_auto_20171217_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='images',
            field=models.ImageField(blank=True, default='user/user_icon.png', upload_to='user/', verbose_name='Фотография'),
        ),
        migrations.AddField(
            model_name='prodact',
            name='images',
            field=models.ImageField(blank=True, default='prodact_icon.png', upload_to='prodact/', verbose_name='Фотография'),
        ),
    ]
