# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-17 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labApp', '0013_auto_20171217_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodact',
            name='images',
            field=models.ImageField(blank=True, default='prodact/prodact_icon.png', upload_to='prodact/', verbose_name='Фотография'),
        ),
    ]
