# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-19 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labApp', '0014_auto_20171217_2013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-order_date',)},
        ),
    ]
