# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-24 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('labApp', '0016_auto_20171223_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата заказа'),
        ),
    ]
