# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-11 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labApp', '0017_auto_20171224_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_price',
            field=models.IntegerField(default=0, verbose_name='Стоимость заказа'),
        ),
    ]
