# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-11 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labApp', '0018_order_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_price',
            field=models.FloatField(default=0, verbose_name='Стоимость заказа'),
        ),
    ]
