# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-20 15:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labApp', '0021_auto_20180112_0139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='images',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='prodact',
            old_name='images',
            new_name='img',
        ),
    ]
