# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-20 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labApp', '0023_auto_20180121_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodact',
            name='description',
            field=models.CharField(max_length=900, null=True, verbose_name='Описание'),
        ),
    ]
